Repository codemaniac-sahil/currency_converter_react, pull requests merged in 2022-10, with the labels that each got.

#17 round the converted amount off to 2 decimal places
  src/components/BannerChart.js
Labels: good first issue, hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted

#20 IMPORTANT SECURITY FIX: Moved API key to environment variable so it i…
  src/App.js
Labels: enhancement, hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted

#30 Website UI design Updated in Readme (#5)
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted

#31 Fix #26. Change Exchange Rates API & Refactor code
  src/App.jsx
  src/components/BannerChart.jsx
  src/components/CurrencyRow.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted
